# Alternative Accelerate configuration for single-machine multi-GPU training
# This configuration is more reliable and avoids NCCL network issues
# Use with: accelerate launch --config_file accelerate_config_single_machine.yaml train_llada_pretrained.py

compute_environment: LOCAL_MACHINE
distributed_type: NO
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_process_ip: localhost
main_process_port: 29500
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

# This configuration will use DataParallel instead of DistributedDataParallel
# which avoids NCCL network issues while still utilizing multiple GPUs
